"""
Data Analysis tab — displays every EDA diagram generated by
shared/eda.py, grouped by theme, with the same captions used in the
written report. Built so this tab can be projected directly during the
presentation instead of switching to the report or opening image files
one by one.
"""

import os

import streamlit as st

from prototype.config import EDA_DIR

# ---------------------------------------------------------------------------
# Each group maps to a section of the report (Section 2.5 / 3.0), so the
# presenter can talk through the same story told in the written report.
# filename -> caption shown under the image.
# ---------------------------------------------------------------------------
GROUPS = [
    {
        "title": "Churn Overview",
        "files": {
            "01_churn_distribution.png": "Figure 1 — Churn Class Distribution "
            "(73.5% No Churn vs 26.5% Churn)",
        },
    },
    {
        "title": "Categorical Drivers of Churn",
        "files": {
            "04_churn_rate_by_category.png": "Figure 2 — Churn Rate by "
            "Contract Type, Internet Service, and Payment Method",
            "11_churn_rate_payment_contract_heatmap.png": "Figure 6 — Churn "
            "Rate by Payment Method and Contract Type",
            "05_contract_tenure_heatmap.png": "Figure 3 — Churn Rate by "
            "Contract Type and Tenure Band",
            "08_churn_rate_streaming.png": "Figure 9 — Churn Rate by "
            "Streaming Services",
            "09_churn_rate_protection_backup.png": "Figure 10 — Churn Rate "
            "by Device Protection and Online Backup",
            "10_churn_rate_total_services.png": "Figure 8 — Churn Rate by "
            "Number of Add-On Services Subscribed",
        },
    },
    {
        "title": "Numeric Relationships",
        "files": {
            "06_correlation_heatmap.png": "Figure 4 — Correlation Heatmap "
            "of Numeric Features",
            "02_numeric_by_churn.png": "Figure 5 — Distribution of Tenure, "
            "Monthly Charges, and Total Charges by Churn Status",
            "12_monthly_vs_total_scatter.png": "Figure 7 — Monthly Charges "
            "vs Total Charges by Churn Status",
        },
    },
    {
        "title": "Outlier Assessment",
        "files": {
            "13_outlier_boxplots_iqr.png": "Outlier Assessment — Boxplots "
            "with IQR Bounds (no outliers found)",
        },
    },
]


def render_analysis_tab() -> None:
    """Entry point called from app.py inside the Data Analysis tab."""
    st.subheader("Exploratory Data Analysis — presentation view")
    st.caption(
        "Every diagram here is generated by `shared/eda.py` and matches "
        "the figures used in Sections 2.5 and 3.0 of the written report."
    )

    if not os.path.isdir(EDA_DIR):
        st.warning(
            "results/eda/ not found. Run `python shared/eda.py` first, "
            "then reload this app."
        )
        return

    # Layout controls
    col1, col2 = st.columns([3, 1])
    with col1:
        group_titles = [g["title"] for g in GROUPS]
        selected_group = st.radio(
            "Jump to a section",
            group_titles,
            horizontal=True,
            key="analysis_group_select",
        )
    with col2:
        num_columns = st.select_slider(
            "Layout",
            options=[1, 2, 3],
            value=1,
            key="analysis_columns",
            help="Choose how many diagrams to display per row"
        )

    st.markdown("---")

    for group in GROUPS:
        if group["title"] != selected_group:
            continue

        missing = []

        # Convert files dict to list for easier indexing
        files_list = list(group["files"].items())

        # Create rows based on selected number of columns
        for row_start in range(0, len(files_list), num_columns):
            cols = st.columns(num_columns)

            for col_idx in range(num_columns):
                file_idx = row_start + col_idx
                if file_idx >= len(files_list):
                    break

                filename, caption = files_list[file_idx]
                path = os.path.join(EDA_DIR, filename)

                if not os.path.exists(path):
                    missing.append(filename)
                    continue

                with cols[col_idx]:
                    st.image(path, caption=caption, use_container_width=True)

        if missing:
            st.info(
                "Not generated yet — run `python shared/eda.py` to create: "
                + ", ".join(missing)
            )
